version: '1.0.{build}'

image: Visual Studio 2017

environment:
  nodejs_version: "6"

platform:
  - x64

configuration:
  - Debug
  - Release

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan
  - conan user
  - conan --version
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version

before_build:
  - md build
  - cd build
  - conan install ..
  - cmake .. -G "Visual Studio 15 2017 Win64"

build:
  project: $(APPVEYOR_BUILD_FOLDER)\build\SeedCpp.sln

after_build:
  - ps: 7z a .\Dist\$env:deploy_name_installer".zip" $env:build_path_installer

test_script:
  - ps: cd bin
  - SeedCppCoreUnitTest.exe --gtest_output=xml:SeedCppCoreUnitTest.xml
  - DatabaseIntegrationTest.exe --gtest_output=xml:DatabaseIntegrationTest.xml
  - ps: cd ..
  - ps: cd ..
  - ps: cd test
  - ps: cd RESTAPITest
  - ps: npm install --no-audit
  - ps: npm run test
  - ps: cd ..
  - ps: cd ..

after_test:
  - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\build\bin\SeedCppCoreUnitTest.xml))
  - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\build\bin\DatabaseIntegrationTest.xml))

artifacts:
  - path: 'build\bin'
    name: SeedCpp