language: cpp

matrix:
  include:
  - os: linux
    dist: xenial
    compiler: gcc
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-7
          - g++-7
    env:
      - BUILD_TYPE=Release
      - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      - COMPILER_LIBCXX=libstdc++11

  - os: osx
    osx_image: xcode10.1
    compiler: clang   
    env:
      - BUILD_TYPE=Release
      - COMPILER_LIBCXX=libc++

install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 90; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90; fi 
  - if [ $TRAVIS_OS_NAME == linux ]; then pip install conan --user; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew install conan; fi
  - conan user

script:
  - mkdir -p build
  - cd build
  - conan install .. -s compiler.libcxx=${COMPILER_LIBCXX}
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} .. 
  - make