language: cpp

matrix:
  include:
  - os: linux
    dist: xenial
    compiler: gcc
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - gcc-7
          - g++-7
    env:
      - BUILD_TYPE=Release
      - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

  - os: osx
    osx_image: xcode10.1
    compiler: clang   
    env:
      - BUILD_TYPE=Release

install: 
  - pip install conan --user
  - conan user

script:
  - mkdir -p build
  - cd build
  - conan install ..
  - cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} .. 
  - make